// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
var aws_app_analytics = 'enable';
var aws_cognito_identity_pool_id = 'ap-southeast-2:51242453-275d-4b84-995d-d0a29becf1e6';
var aws_cognito_region = 'ap-southeast-2';
var aws_content_delivery = 'enable';
var aws_content_delivery_bucket = 'quizesweb-hosting-mobilehub-336633224';
var aws_content_delivery_bucket_region = 'ap-southeast-2';
var aws_content_delivery_cloudfront = 'enable';
var aws_content_delivery_cloudfront_domain = 'd1pgqs3q10yg7w.cloudfront.net';
var aws_mobile_analytics_app_id = 'a84c3b2f3ec44e2e8cae288f6c854940';
var aws_mobile_analytics_app_region = 'us-east-1';
var aws_project_id = '12be5feb-5efe-4edc-8ee9-cbf5f5330548';
var aws_project_name = 'Quizes-Web';
var aws_project_region = 'ap-southeast-2';
var aws_resource_name_prefix = 'quizesweb-mobilehub-336633224';

AWS.config.region = aws_project_region;
AWS.config.credentials = new AWS.CognitoIdentityCredentials({
    IdentityPoolId: aws_cognito_identity_pool_id
  }, {
    region: aws_cognito_region
  });
AWS.config.update({customUserAgent: 'MobileHub v0.1'});
