// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'ap-southeast-2:51242453-275d-4b84-995d-d0a29becf1e6',
    'aws_cognito_region': 'ap-southeast-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'quizesweb-hosting-mobilehub-336633224',
    'aws_content_delivery_bucket_region': 'ap-southeast-2',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd1pgqs3q10yg7w.cloudfront.net',
    'aws_mobile_analytics_app_id': 'a84c3b2f3ec44e2e8cae288f6c854940',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '12be5feb-5efe-4edc-8ee9-cbf5f5330548',
    'aws_project_name': 'Quizes-Web',
    'aws_project_region': 'ap-southeast-2',
    'aws_resource_name_prefix': 'quizesweb-mobilehub-336633224',
}

export default awsmobile;
